config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/home', to: "homes#index"
  get '/logout', to: "logouts#index"
  resources :homes do
    resources :comments, only: [:create]
  end
  resources :logouts
  resources :timelines
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :home
  belongs_to :user
  include ActionView::RecordIdentifier

after_create_commit { broadcast_prepend_to [home, :comments], target: "#{dom_id(home)}_comments" }
  
end

app/models/home.rb
class Home < ApplicationRecord

  has_many :comments, dependent: :destroy
  belongs_to :user
    has_many_attached :music
    has_one_attached :image
    has_many_attached :images
  has_one_attached :video
  has_one_attached :photo
end

app/models/logout.rb
class Logout < ApplicationRecord
end

app/models/timeline.rb
class Timeline < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one_attached :image
         has_many :homes, dependent: :destroy
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :set_active_storage_url_options

    private
  
    def set_active_storage_url_options
      ActiveStorage::Current.url_options = { host: request.base_url }
    end
    
    protected
    
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :username, :gender, :image])
      devise_parameter_sanitizer.permit(:account_update, keys: [:full_name, :username, :gender, :image])
    end
    end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @home = Home.find(params[:home_id])
    @comment = current_user.comments.new(comment_params.merge(home_id: @home.id))

    respond_to do |format|
      if @comment.save
        format.turbo_stream { render turbo_stream: turbo_stream.replace('comment_form', partial: 'comments/form', locals: { comment: Comment.new }) }
        format.html { render partial: 'comments/form', locals: { comment: Comment.new }}
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace('comment_form', partial: 'comments/form', locals: { comment: @comment }) }
        format.html { render partial: 'comments/form', locals: { comment: @comment }}
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: %i[ show edit update destroy ]

  # GET /homes or /homes.json
  def index
    @homes = Home.all.order(created_at: :desc)
    @user = current_user
    
  end

  # GET /homes/1 or /homes/1.json
  def show
    @home = Home.find(params[:id])
    @homes = Home.all # Or whatever logic to fetch homes
     @user = current_user
     if @home.user == current_user
      @user = current_user
    else
      redirect_to root_path, notice: 'Post not found'
    end
  end

  # GET /homes/new
  def new
    @home = Home.new
    @home = current_user.homes.build
  end

   # GET /homes/1/edit
   def edit
    redirect_to root_path, notice: 'Access denied' unless @home.user == current_user
  end

  # POST /homes or /homes.json
  def create
    @home = Home.new(home_params)
    @home = current_user.homes.build(home_params)
    respond_to do |format|
      if @home.save
        format.html { redirect_to root_path, notice: "Home was successfully created." }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1 or /homes/1.json
  def update
    respond_to do |format|
      if @home.user == current_user && @home.update(home_params)
        format.html { redirect_to root_path(@home), notice: "Home was successfully updated." }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /homes/1 or /homes/1.json
  def destroy
    if @home.user == current_user
      @home.destroy!
      respond_to do |format|
        format.html { redirect_to homes_url, notice: "Home was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to root_path, notice: 'Access denied'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_params
      params.require(:home).permit(:content, :music, :video, :photo, image: [], images: [])
    end
end

app/controllers/logouts_controller.rb
class LogoutsController < ApplicationController
    def index
        @user = current_user
        # Additional logic as needed
      end
end

app/controllers/timelines_controller.rb
# app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
    def index
        @homes = Home.all
      @user = current_user  
      # Other logic here
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/logouts_helper.rb
module LogoutsHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/views/comments/12.html.erb
<%= turbo_frame_tag "comment_form" do %>
  <%= form_with model: comment, url: home_comments_path(@home) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
          <% comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form.text_field :body %>
    <%= form.submit %>
  <% end %>
<% end %>

app/views/comments/_comment.html.erb
<!-- app/views/comments/_comment.html.erb -->

<div id="<%= dom_id(comment) %>">
  <%= comment.body %>
</div>
  

app/views/comments/_form.html.erb
<!-- app/views/comments/_form.html.erb -->

<%= turbo_frame_tag "comment_form" do %>
  <%= form_with model: comment, url: home_comments_path(home) do |form| %>
    
     
    
   <%= form.text_area :body, placeholder: "Post your comment" %>
   
    <%= form.submit "Comments"%>
  <% end %>
<% end %>

  

app/views/homes/_form.html.erb
<%= form_tag({ controller: "homes", action: "create" }, method: "post", multipart: true) do %>
												<textarea rows="2" placeholder="write something" name="home[content]"></textarea>
												<div class="attachments">
													<ul>
													<li>
														<div id="music-preview"></div>
														<i class="bi bi-music-note-beamed"></i>
														<label class="fileContainer">
														<%= file_field_tag "home[music]", class: "file-input", accept: "audio/*" %>
														</label>
													</li>
													<li>
														<div id="image-preview"></div>
														<i class="bi bi-image"></i>
														<label class="fileContainer">
														<%= file_field_tag "home[image]", class: "file-input", accept: "image/*" %>
													<%= file_field_tag "home[images][]", class: "file-input", accept: "image/*", multiple: true %>
														</label>
													</li>
													<li>
														<div id="video-preview"></div>
														<i class="bi bi-camera-reels-fill"></i>
														<label class="fileContainer">
														<%= file_field_tag "home[video]", class: "file-input", accept: "video/*" %>
														</label>
													</li>
													<li>
														<i class="bi bi-camera-fill"></i>
														<label class="fileContainer">
														<%= file_field_tag "home[photo]", class: "file-input", accept: "image/*" %>
														</label>
														<div id="photo-preview"></div> <!-- Container for photo preview -->
													</li>
													<li>
<%= submit_tag "Post", class: "blue-button" %>

													</li>
													</ul>
												</div>
											<% end %>

app/views/homes/_home.html.erb
<div id="<%= dom_id home %>">
  

</div>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render "form", home: @home %>

<br>

<div>
  <%= link_to "Show this home", @home %> |
  <%= link_to "Back to homes", homes_path %>
</div>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render "form", home: @home %>

<br>

<div>
  <%= link_to "Back to homes", homes_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apps</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<meta name="csrf-token" content="<%= form_authenticity_token %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-xxx" crossorigin="anonymous" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/themify-icons/0.1.2/css/themify-icons.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'backgroundVideo' %>
  <%= javascript_include_tag 'custom' %>
  <%= javascript_include_tag 'echarts.min' %>
  <%= javascript_include_tag 'main.min' %>
  <%= javascript_include_tag 'map-init' %>
  <%= javascript_include_tag 'script' %>
  <%= javascript_include_tag 'strip.pkgd.min' %>
  <%= javascript_include_tag 'userincr' %>
  <%= javascript_include_tag 'world' %>
 
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  </head>

  <body>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<nav>
    <% if user_signed_in? %>
      <!-- Display links when user is signed in -->
      <%= link_to 'Sign Out', destroy_user_session_path,
  data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
    <% else %>
      <!-- Display links when user is not signed in -->
      <%= link_to 'Sign in', new_user_session_path %>
      <%= link_to 'Sign up', new_user_registration_path %>
    <% end %>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/logouts/index.html.erb
<div class="theme-layout">
	
	<div class="responsive-header">
		<div class="mh-head first Sticky">
			<span class="mh-btns-left">
				<a class="" href="#menu"><i class="fa fa-align-justify"></i></a>
			</span>
			<span class="mh-text">
				<a href="newsfeed.html" title=""><img src="images/logo2.png" alt=""></a>
			</span>
			<span class="mh-btns-right">
				<a class="fa fa-sliders" href="#shoppingbag"></a>
			</span>
		</div>
		<div class="mh-head second">
			<form class="mh-form">
				<input placeholder="search" />
				<a href="#/" class="fa fa-search"></a>
			</form>
		</div>
		<nav id="menu" class="res-menu">
			<ul>
				<li><span>Home</span>
					<ul>
						<li><a href="index-2.html" title="">Home Social</a></li>
						<li><a href="index2.html" title="">Home Social 2</a></li>
						<li><a href="index-company.html" title="">Home Company</a></li>
						<li><a href="landing.html" title="">Login page</a></li>
						<li><a href="logout.html" title="">Logout Page</a></li>
						<li><a href="newsfeed.html" title="">news feed</a></li>
					</ul>
				</li>
				<li><span>Time Line</span>
					<ul>
						<li><a href="time-line.html" title="">timeline</a></li>
						<li><a href="timeline-friends.html" title="">timeline friends</a></li>
						<li><a href="timeline-groups.html" title="">timeline groups</a></li>
						<li><a href="timeline-pages.html" title="">timeline pages</a></li>
						<li><a href="timeline-photos.html" title="">timeline photos</a></li>
						<li><a href="timeline-videos.html" title="">timeline videos</a></li>
						<li><a href="fav-page.html" title="">favourit page</a></li>
						<li><a href="groups.html" title="">groups page</a></li>
						<li><a href="page-likers.html" title="">Likes page</a></li>
						<li><a href="people-nearby.html" title="">people nearby</a></li>
						
						
					</ul>
				</li>
				<li><span>Account Setting</span>
					<ul>
						<li><a href="create-fav-page.html" title="">create fav page</a></li>
						<li><a href="edit-account-setting.html" title="">edit account setting</a></li>
						<li><a href="edit-interest.html" title="">edit-interest</a></li>
						<li><a href="edit-password.html" title="">edit-password</a></li>
						<li><a href="edit-profile-basic.html" title="">edit profile basics</a></li>
						<li><a href="edit-work-eductation.html" title="">edit work educations</a></li>
						<li><a href="messages.html" title="">message box</a></li>
						<li><a href="inbox.html" title="">Inbox</a></li>
						<li><a href="notifications.html" title="">notifications page</a></li>
					</ul>
				</li>
				<li><span>forum</span>
					<ul>
						<li><a href="forum.html" title="">Forum Page</a></li>
						<li><a href="forums-category.html" title="">Fourm Category</a></li>
						<li><a href="forum-open-topic.html" title="">Forum Open Topic</a></li>
						<li><a href="forum-create-topic.html" title="">Forum Create Topic</a></li>
					</ul>
				</li>
				<li><span>Our Shop</span>
					<ul>
						<li><a href="shop.html" title="">Shop Products</a></li>
						<li><a href="shop-masonry.html" title="">Shop Masonry Products</a></li>
						<li><a href="shop-single.html" title="">Shop Detail Page</a></li>
						<li><a href="shop-cart.html" title="">Shop Product Cart</a></li>
						<li><a href="shop-checkout.html" title="">Product Checkout</a></li>
					</ul>
				</li>
				<li><span>Our Blog</span>
					<ul>
						<li><a href="blog-grid-wo-sidebar.html" title="">Our Blog</a></li>
						<li><a href="blog-grid-right-sidebar.html" title="">Blog with R-Sidebar</a></li>
						<li><a href="blog-grid-left-sidebar.html" title="">Blog with L-Sidebar</a></li>
						<li><a href="blog-masonry.html" title="">Blog Masonry Style</a></li>
						<li><a href="blog-list-wo-sidebar.html" title="">Blog List Style</a></li>
						<li><a href="blog-list-right-sidebar.html" title="">Blog List with R-Sidebar</a></li>
						<li><a href="blog-list-left-sidebar.html" title="">Blog List with L-Sidebar</a></li>
						<li><a href="blog-detail.html" title="">Blog Post Detail</a></li>
					</ul>
				</li>
				<li><span>Portfolio</span>
					<ul>
						<li><a href="portfolio-2colm.html" title="">Portfolio 2col</a></li>
						<li><a href="portfolio-3colm.html" title="">Portfolio 3col</a></li>
						<li><a href="portfolio-4colm.html" title="">Portfolio 4col</a></li>
					</ul>
				</li>
				<li><span>Support & Help</span>
					<ul>
						<li><a href="support-and-help.html" title="">Support & Help</a></li>
						<li><a href="support-and-help-detail.html" title="">Support & Help Detail</a></li>
						<li><a href="support-and-help-search-result.html" title="">Support & Help Search Result</a></li>
					</ul>
				</li>
				<li><span>More pages</span>
					<ul>
						<li><a href="careers.html" title="">Careers</a></li>
						<li><a href="career-detail.html" title="">Career Detail</a></li>
						<li><a href="404.html" title="">404 error page</a></li>
						<li><a href="404-2.html" title="">404 Style2</a></li>
						<li><a href="faq.html" title="">faq's page</a></li>
						<li><a href="insights.html" title="">insights</a></li>
						<li><a href="knowledge-base.html" title="">knowledge base</a></li>
					</ul>
				</li>
				<li><a href="about.html" title="">about</a></li>
				<li><a href="about-company.html" title="">About Us2</a></li>
				<li><a href="contact.html" title="">contact</a></li>
				<li><a href="contact-branches.html" title="">Contact Us2</a></li>
				<li><a href="widgets.html" title="">Widgts</a></li>
			</ul>
		</nav>
		<nav id="shoppingbag">
			<div>
				<div class="">
					<form method="post">
						<div class="setting-row">
							<span>use night mode</span>
							<input type="checkbox" id="nightmode"/> 
							<label for="nightmode" data-on-label="ON" data-off-label="OFF"></label>
						</div>
						<div class="setting-row">
							<span>Notifications</span>
							<input type="checkbox" id="switch2"/> 
							<label for="switch2" data-on-label="ON" data-off-label="OFF"></label>
						</div>
						<div class="setting-row">
							<span>Notification sound</span>
							<input type="checkbox" id="switch3"/> 
							<label for="switch3" data-on-label="ON" data-off-label="OFF"></label>
						</div>
						<div class="setting-row">
							<span>My profile</span>
							<input type="checkbox" id="switch4"/> 
							<label for="switch4" data-on-label="ON" data-off-label="OFF"></label>
						</div>
						<div class="setting-row">
							<span>Show profile</span>
							<input type="checkbox" id="switch5"/> 
							<label for="switch5" data-on-label="ON" data-off-label="OFF"></label>
						</div>
					</form>
					<h4 class="panel-title">Account Setting</h4>
					<form method="post">
						<div class="setting-row">
							<span>Sub users</span>
							<input type="checkbox" id="switch6" /> 
							<label for="switch6" data-on-label="ON" data-off-label="OFF"></label>
						</div>
						<div class="setting-row">
							<span>personal account</span>
							<input type="checkbox" id="switch7" /> 
							<label for="switch7" data-on-label="ON" data-off-label="OFF"></label>
						</div>
						<div class="setting-row">
							<span>Business account</span>
							<input type="checkbox" id="switch8" /> 
							<label for="switch8" data-on-label="ON" data-off-label="OFF"></label>
						</div>
						<div class="setting-row">
							<span>Show me online</span>
							<input type="checkbox" id="switch9" /> 
							<label for="switch9" data-on-label="ON" data-off-label="OFF"></label>
						</div>
						<div class="setting-row">
							<span>Delete history</span>
							<input type="checkbox" id="switch10" /> 
							<label for="switch10" data-on-label="ON" data-off-label="OFF"></label>
						</div>
						<div class="setting-row">
							<span>Expose author name</span>
							<input type="checkbox" id="switch11" /> 
							<label for="switch11" data-on-label="ON" data-off-label="OFF"></label>
						</div>
					</form>
				</div>
			</div>
		</nav>
	</div><!-- responsive header -->
	
	<div class="topbar stick">
		<div class="logo">
			<a title="" href="newsfeed.html"><%= image_tag("logo.png", alt: "Logo") %></a>
		</div>
		
		<div class="top-area">
			<div class="top-search">
				<form method="post" class="">
					<input type="text" placeholder="Search Friend">
					<button data-ripple><i class="ti-search"></i></button>
				</form>
			</div>
			<div class="login-form">
				<form method="post">
					<input type="text" placeholder="User Name">
					<input type="password" placeholder="Passoword">
					<button type="submit">Login</button>
				</form>
			</div>
		</div>
	</div><!-- topbar with logout -->
	
	<section>
		<div class="feature-photo">
			<figure><%= image_tag("resources/timeline-1.jpg", alt: "Logo") %>
                <img alt="" src="images/resources/timeline-1.jpg"></figure>
			<div class="add-btn">
				<span>1205 followers</span>
				<a data-ripple="" title="" href="#">Add Friend</a>
			</div>
			<form class="edit-phto">
				<i class="fa fa-camera-retro"></i>
				<label class="fileContainer">
					Edit Cover Photo
				<input type="file">
				</label>
			</form>
			<div class="container-fluid">
				<div class="row merged">
					<div class="col-lg-2 col-sm-3">
						<div class="user-avatar">
							<figure>
								<%= image_tag @user.image if @user.image.attached? %>
								<form class="edit-phto">
									<i class="fa fa-camera-retro"></i>
									<label class="fileContainer">
										Edit Display Photo
										<input type="file">
									</label>
								</form>
							</figure>
						</div>
					</div>
					<div class="col-lg-10 col-sm-9">
						<div class="timeline-info">
							<ul>
								<li class="admin-name">
								  <h5>Janice Griffith</h5>
								  <span>Group Admin</span>
								</li>
								<li>
									<a data-ripple="" title="" href="time-line.html" class="active">time line</a>
									<a data-ripple="" title="" href="timeline-photos.html" class="">Photos</a>
									<a data-ripple="" title="" href="timeline-videos.html" class="">Videos</a>
									<a data-ripple="" title="" href="timeline-friends.html" class="">Friends</a>
									<a data-ripple="" title="" href="timeline-groups.html" class="">Groups</a>
									<a data-ripple="" title="" href="about.html" class="">about</a>
									<a data-ripple="" title="" href="#" class="">more</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
		
	<section>
		<div class="gap100 gray-bg">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="logout-meta">
							<h2>logged out</h2>
							<span>Do you want to check Janice Griffith’s Profile?</span>
							<p>
								Please <a href="landing.html" title="">Login</a> or <a href="landing.html" title="">Register</a> now to create your own profile and have access to all the Winku awesome features!
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>	
	</section>

	<div class="bottombar">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<span class="copyright"><a target="_blank" href="https://www.templateshub.net">Templates Hub</a></span>
					<i><img src="images/credit-cards.png" alt=""></i>
				</div>
			</div>
		</div>
	</div>
</div>	

app/views/shared/_emojis.html.erb
<% emojis.each do |emoji| %>
  <span class="emoji" title="<%= emoji.name %>"><%= raw emoji.raw %></span>
<% end %>